# Generated by Django 4.2.27 on 2026-01-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newstories', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
