# Generated by Django 4.2.27 on 2026-01-29 00:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newstories', '0005_articlevote'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
